### ISSUE TITLE
Services Listing : An unknown/garbage character was displayed. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/NWSP#101]
See page link: 
http://nwsp.stage.titanweb.com.au/services_category/service-5-category-title-goes-here-for-two-or-more-lines/

![image](https://cloud.githubusercontent.com/assets/12791909/9650274/39bd63fc-5233-11e5-8b5b-e72312d402a9.png)

**Comment by ganesh-titan** [comment]
FYI : These Characters coming from Test-Content.
