### ISSUE TITLE
Banner: Banner description were displayed on the front-end, which is not found in the design and not specified in the project scope.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/NWSP#7]
![image](https://cloud.githubusercontent.com/assets/12791909/9485203/7d50d906-4be8-11e5-9566-ad0019894e14.png)

**Comment by ermatitan** [comment]
not fix.

**Comment by ganesh-titan** [comment]
![image](https://cloud.githubusercontent.com/assets/13450883/9660226/2149e68a-5272-11e5-80ce-b94a8fcb3cc4.png)

**Comment by ganesh-titan** [comment]
FYI : As per design we are implemented.These content coming from banner description.
