### ISSUE TITLE
Services - clicking on the pagination next page will result to a page not found error

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/NWSP#96]
![image](https://cloud.githubusercontent.com/assets/12791909/9649622/1b91e064-522a-11e5-98cc-47e86bab59b4.png)

**Comment by ermatitan** [comment]
not fix

**Comment by ganesh-titan** [comment]
FYI : Please once re-check , But it's working fine.

**Comment by ganesh-titan** [comment]
Updated.
